#### Numpy 배열의 연산:

리스트 연산과 Numpy 배열의 연산 비교:

In [10]:
import numpy as np

In [11]:
a = [1, 2, 3]

In [12]:
a + a

[1, 2, 3, 1, 2, 3]

In [13]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [14]:
b = np.array([1, 2, 3])

In [15]:
b*3

array([3, 6, 9])

In [16]:
b + b

array([2, 4, 6])

In [17]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

Numpy 배열의 연산:

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [19]:
a+b

array([5, 7, 9])

In [20]:
a-b

array([-3, -3, -3])

In [21]:
a*b

array([ 4, 10, 18])

In [ ]:
1.0*a/b

연산의 벡터화:

In [22]:
x = np.array([0, 1, 2, 3])

In [23]:
pow(10, x) #10 ** 0 , 10 ** 1, 10 ** 2, 10 ** 3

array([   1,   10,  100, 1000], dtype=int32)

In [24]:
x**3   #제곱

array([ 0,  1,  8, 27], dtype=int32)

In [25]:
np.sqrt(x) #제곱근 함수

array([ 0.        ,  1.        ,  1.41421356,  1.73205081])

In [26]:
np.exp(x) #상수 e^x값 반영 e(2.71828) x X값

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692])

메서드로 제공되는 통계함수:

In [27]:
x=np.arange(1,11)

In [28]:
x.sum()

55

In [29]:
x.mean()

5.5

In [30]:
x.std() #표준편차

2.8722813232690143

In [31]:
x.var() #분산

8.25

In [33]:
x.cumsum()     #누적합

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [34]:
y = np.arange(1,10)
y = y.reshape((3,-1))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(y.mean(axis=0))

In [ ]:
print(y.mean(axis=1))

In [ ]:
np.random.seed(123)
z = np.random.randint(10,size=1000)

In [ ]:
z.max()

In [ ]:
z.min()

In [ ]:
(z > 5).sum()

In [ ]:
np.unique(z)

In [ ]:
sorted(set(z))