#### Numpy 행렬과 선형대수학:

In [4]:
import numpy as np

내적 구하기:

In [29]:
x = np.array([1, 3, 5])
y = np.array([2, 4, 6])

In [3]:
np.dot(x,y)

44

In [4]:
x.dot(y)

44

In [5]:
np.sum(x*y)

44

dot 연산자:

In [5]:
x = np.array([1, 3, 5])
y = np.array([2, 4, 6])
x = x.reshape((3,1))
y = y.reshape((1,3))
print("{}".format(x))
print(" ----------")
print("{}".format(y))

[[1]
 [3]
 [5]]
 ----------
[[2 4 6]]


In [7]:
y.dot(x)[0,0]

44

In [8]:
x.dot(y)

array([[ 2,  4,  6],
       [ 6, 12, 18],
       [10, 20, 30]])

행렬 만들기

In [9]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [10]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [11]:
np.random.seed(222) #222이라는 수를 근본으로 난수 생성
np.random.random((2,2))

array([[ 0.52602843,  0.68531719],
       [ 0.83567419,  0.65376526]])

In [12]:
np.random.seed(111)
np.random.randn(2,2)

array([[-1.13383833,  0.38431919],
       [ 1.49655378, -0.3553823 ]])

In [13]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

행렬의 연산 (행렬과 행렬):

In [58]:
m1 = np.array([[1, 2, 3],[4, 5, 6]])
m2 = np.array([[6, 5, 4],[3, 2, 1]])


In [36]:
print(m1)

[[1 2 3]
 [4 5 6]]


In [15]:
m1+m2

array([[7, 7, 7],
       [7, 7, 7]])

In [32]:
m1*m2

array([[ 6, 10, 12],
       [12, 10,  6]])

In [17]:
np.transpose(m2)

array([[6, 3],
       [5, 2],
       [4, 1]])

In [18]:
np.dot(m1,np.transpose(m2))

array([[28, 10],
       [73, 28]])

행렬의 연산 (행렬과 스칼라):

In [19]:
m = np.array([[1, 2],[3, 4]])

In [20]:
m*3

array([[ 3,  6],
       [ 9, 12]])

In [ ]:
m/2

In [ ]:
m+1

역행렬:

In [23]:
m = np.array([[1, 2],[3, 4]])
minv = np.linalg.inv(m)
minv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [24]:
mres = np.dot(m, minv)
np.round(mres,2) 

array([[ 1.,  0.],
       [ 0.,  1.]])

연립 방정식: 이 경우에는 선형 방정식의 갯수 = 미지수의 갯수.

In [21]:
A = np.array([[5, 8],[6, 4]])
b = np.array([[30], [25]])
Ainv = np.linalg.inv(A)
print(np.dot(Ainv,b))

[[ 2.85714286]
 [ 1.96428571]]


In [22]:
np.linalg.solve(A, b)

array([[ 2.85714286],
       [ 1.96428571]])

In [71]:
A = np.array([[1, 4, 6],[3, 7, 9]])
B = np.array([[7, 6],[3, 7]])
C = np.array([[1, 0],[3, 1], [2, 3]])
print(A)
print(B)
print(C)

[[1 4 6]
 [3 7 9]]
[[7 6]
 [3 7]]
[[1 0]
 [3 1]
 [2 3]]


In [72]:
A.dot(C)

array([[25, 22],
       [42, 34]])

In [68]:
np.transpose(C)

array([[1, 3, 2],
       [0, 1, 3]])

In [70]:
A * np.transpose(C)

array([[ 1, 12, 12],
       [ 0,  7, 27]])